// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbpipes/proto/bigquery_schema.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "pbpipes/proto/bigquery_schema.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace pbpipes {
namespace proto {

namespace {


}  // namespace


void protobuf_AssignDesc_pbpipes_2fproto_2fbigquery_5fschema_2eproto() {
  protobuf_AddDesc_pbpipes_2fproto_2fbigquery_5fschema_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "pbpipes/proto/bigquery_schema.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_pbpipes_2fproto_2fbigquery_5fschema_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_pbpipes_2fproto_2fbigquery_5fschema_2eproto() {
}

void protobuf_AddDesc_pbpipes_2fproto_2fbigquery_5fschema_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fdescriptor_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n#pbpipes/proto/bigquery_schema.proto\022\rp"
    "bpipes.proto\032 google/protobuf/descriptor"
    ".proto:8\n\016bigquery_table\022\037.google.protob"
    "uf.MessageOptions\030\213\010 \001(\t", 144);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "pbpipes/proto/bigquery_schema.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::MessageOptions::default_instance(),
    1035, 9, false, false);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_pbpipes_2fproto_2fbigquery_5fschema_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_pbpipes_2fproto_2fbigquery_5fschema_2eproto {
  StaticDescriptorInitializer_pbpipes_2fproto_2fbigquery_5fschema_2eproto() {
    protobuf_AddDesc_pbpipes_2fproto_2fbigquery_5fschema_2eproto();
  }
} static_descriptor_initializer_pbpipes_2fproto_2fbigquery_5fschema_2eproto_;
const ::std::string bigquery_table_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  bigquery_table(kBigqueryTableFieldNumber, bigquery_table_default);

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace pbpipes

// @@protoc_insertion_point(global_scope)
