// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: proto/pbpipes.proto

#include "proto/pbpipes.pb.h"
#include "proto/pbpipes.grpc.pb.h"

#include <grpc++/channel.h>
#include <grpc++/impl/client_unary_call.h>
#include <grpc++/impl/rpc_service_method.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/support/async_unary_call.h>
#include <grpc++/support/async_stream.h>
#include <grpc++/support/sync_stream.h>
namespace pbpipes {
namespace proto {

static const char* Executor_method_names[] = {
  "/pbpipes.proto.Executor/PostTask",
};

std::unique_ptr< Executor::Stub> Executor::NewStub(const std::shared_ptr< ::grpc::Channel>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< Executor::Stub> stub(new Executor::Stub(channel));
  return stub;
}

Executor::Stub::Stub(const std::shared_ptr< ::grpc::Channel>& channel)
  : channel_(channel), rpcmethod_PostTask_(Executor_method_names[0], ::grpc::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Executor::Stub::PostTask(::grpc::ClientContext* context, const ::pbpipes::proto::TaskInfo& request, ::pbpipes::proto::TaskResult* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_PostTask_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::pbpipes::proto::TaskResult>* Executor::Stub::AsyncPostTaskRaw(::grpc::ClientContext* context, const ::pbpipes::proto::TaskInfo& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::pbpipes::proto::TaskResult>(channel_.get(), cq, rpcmethod_PostTask_, context, request);
}

Executor::AsyncService::AsyncService() : ::grpc::AsynchronousService(Executor_method_names, 1) {}

Executor::Service::Service() {
}

Executor::Service::~Service() {
}

::grpc::Status Executor::Service::PostTask(::grpc::ServerContext* context, const ::pbpipes::proto::TaskInfo* request, ::pbpipes::proto::TaskResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

void Executor::AsyncService::RequestPostTask(::grpc::ServerContext* context, ::pbpipes::proto::TaskInfo* request, ::grpc::ServerAsyncResponseWriter< ::pbpipes::proto::TaskResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
  AsynchronousService::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
}

::grpc::RpcService* Executor::Service::service() {
  if (service_) {
    return service_.get();
  }
  service_ = std::unique_ptr< ::grpc::RpcService>(new ::grpc::RpcService());
  service_->AddMethod(new ::grpc::RpcServiceMethod(
      Executor_method_names[0],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< Executor::Service, ::pbpipes::proto::TaskInfo, ::pbpipes::proto::TaskResult>(
          std::mem_fn(&Executor::Service::PostTask), this)));
  return service_.get();
}


}  // namespace pbpipes
}  // namespace proto

