// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: proto/pbpipes.proto
#ifndef GRPC_proto_2fpbpipes_2eproto__INCLUDED
#define GRPC_proto_2fpbpipes_2eproto__INCLUDED

#include "proto/pbpipes.pb.h"

#include <grpc++/support/async_stream.h>
#include <grpc++/impl/rpc_method.h>
#include <grpc++/impl/proto_utils.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/support/async_unary_call.h>
#include <grpc++/support/status.h>
#include <grpc++/support/stub_options.h>
#include <grpc++/support/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace pbpipes {
namespace proto {

class Executor GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status PostTask(::grpc::ClientContext* context, const ::pbpipes::proto::TaskInfo& request, ::pbpipes::proto::TaskResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pbpipes::proto::TaskResult>> AsyncPostTask(::grpc::ClientContext* context, const ::pbpipes::proto::TaskInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pbpipes::proto::TaskResult>>(AsyncPostTaskRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pbpipes::proto::TaskResult>* AsyncPostTaskRaw(::grpc::ClientContext* context, const ::pbpipes::proto::TaskInfo& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::Channel>& channel);
    ::grpc::Status PostTask(::grpc::ClientContext* context, const ::pbpipes::proto::TaskInfo& request, ::pbpipes::proto::TaskResult* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pbpipes::proto::TaskResult>> AsyncPostTask(::grpc::ClientContext* context, const ::pbpipes::proto::TaskInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pbpipes::proto::TaskResult>>(AsyncPostTaskRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::Channel> channel_;
    ::grpc::ClientAsyncResponseReader< ::pbpipes::proto::TaskResult>* AsyncPostTaskRaw(::grpc::ClientContext* context, const ::pbpipes::proto::TaskInfo& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_PostTask_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::Channel>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::SynchronousService {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status PostTask(::grpc::ServerContext* context, const ::pbpipes::proto::TaskInfo* request, ::pbpipes::proto::TaskResult* response);
    ::grpc::RpcService* service() GRPC_OVERRIDE GRPC_FINAL;
   private:
    std::unique_ptr< ::grpc::RpcService> service_;
  };
  class AsyncService GRPC_FINAL : public ::grpc::AsynchronousService {
   public:
    explicit AsyncService();
    ~AsyncService() {};
    void RequestPostTask(::grpc::ServerContext* context, ::pbpipes::proto::TaskInfo* request, ::grpc::ServerAsyncResponseWriter< ::pbpipes::proto::TaskResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
  };
};

}  // namespace proto
}  // namespace pbpipes


#endif  // GRPC_proto_2fpbpipes_2eproto__INCLUDED
