# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/pbpipes.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/pbpipes.proto',
  package='pbpipes.proto',
  syntax='proto3',
  serialized_pb=b'\n\x13proto/pbpipes.proto\x12\rpbpipes.proto\"\x83\x01\n\x0fHBaseRegionInfo\x12\x11\n\tstart_key\x18\x01 \x01(\x0c\x12\x0f\n\x07\x65nd_key\x18\x02 \x01(\x0c\x12\n\n\x02id\x18\x03 \x01(\x03\x12\x0c\n\x04name\x18\x04 \x01(\x0c\x12\x0f\n\x07version\x18\x05 \x01(\x05\x12\x13\n\x0bserver_name\x18\x06 \x01(\x0c\x12\x0c\n\x04port\x18\x07 \x01(\x05\"X\n\x08TaskInfo\x12\r\n\x05index\x18\x01 \x01(\x05\x12\r\n\x05total\x18\x02 \x01(\x05\x12.\n\x06region\x18\x03 \x01(\x0b\x32\x1e.pbpipes.proto.HBaseRegionInfo\"\x18\n\nTaskResult\x12\n\n\x02ok\x18\x01 \x01(\x08\"3\n\x0c\x45xecutorSpec\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x15\n\rnum_executors\x18\x02 \x01(\x05\">\n\x0c\x44riverConfig\x12.\n\texecutors\x18\x01 \x03(\x0b\x32\x1b.pbpipes.proto.ExecutorSpec2J\n\x08\x45xecutor\x12>\n\x08PostTask\x12\x17.pbpipes.proto.TaskInfo\x1a\x19.pbpipes.proto.TaskResultb\x06proto3'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HBASEREGIONINFO = _descriptor.Descriptor(
  name='HBaseRegionInfo',
  full_name='pbpipes.proto.HBaseRegionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_key', full_name='pbpipes.proto.HBaseRegionInfo.start_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_key', full_name='pbpipes.proto.HBaseRegionInfo.end_key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='pbpipes.proto.HBaseRegionInfo.id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='pbpipes.proto.HBaseRegionInfo.name', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='pbpipes.proto.HBaseRegionInfo.version', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_name', full_name='pbpipes.proto.HBaseRegionInfo.server_name', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='pbpipes.proto.HBaseRegionInfo.port', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=170,
)


_TASKINFO = _descriptor.Descriptor(
  name='TaskInfo',
  full_name='pbpipes.proto.TaskInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='pbpipes.proto.TaskInfo.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total', full_name='pbpipes.proto.TaskInfo.total', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='region', full_name='pbpipes.proto.TaskInfo.region', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=260,
)


_TASKRESULT = _descriptor.Descriptor(
  name='TaskResult',
  full_name='pbpipes.proto.TaskResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='pbpipes.proto.TaskResult.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=286,
)


_EXECUTORSPEC = _descriptor.Descriptor(
  name='ExecutorSpec',
  full_name='pbpipes.proto.ExecutorSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='pbpipes.proto.ExecutorSpec.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_executors', full_name='pbpipes.proto.ExecutorSpec.num_executors', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=339,
)


_DRIVERCONFIG = _descriptor.Descriptor(
  name='DriverConfig',
  full_name='pbpipes.proto.DriverConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='executors', full_name='pbpipes.proto.DriverConfig.executors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=403,
)

_TASKINFO.fields_by_name['region'].message_type = _HBASEREGIONINFO
_DRIVERCONFIG.fields_by_name['executors'].message_type = _EXECUTORSPEC
DESCRIPTOR.message_types_by_name['HBaseRegionInfo'] = _HBASEREGIONINFO
DESCRIPTOR.message_types_by_name['TaskInfo'] = _TASKINFO
DESCRIPTOR.message_types_by_name['TaskResult'] = _TASKRESULT
DESCRIPTOR.message_types_by_name['ExecutorSpec'] = _EXECUTORSPEC
DESCRIPTOR.message_types_by_name['DriverConfig'] = _DRIVERCONFIG

HBaseRegionInfo = _reflection.GeneratedProtocolMessageType('HBaseRegionInfo', (_message.Message,), dict(
  DESCRIPTOR = _HBASEREGIONINFO,
  __module__ = 'proto.pbpipes_pb2'
  # @@protoc_insertion_point(class_scope:pbpipes.proto.HBaseRegionInfo)
  ))
_sym_db.RegisterMessage(HBaseRegionInfo)

TaskInfo = _reflection.GeneratedProtocolMessageType('TaskInfo', (_message.Message,), dict(
  DESCRIPTOR = _TASKINFO,
  __module__ = 'proto.pbpipes_pb2'
  # @@protoc_insertion_point(class_scope:pbpipes.proto.TaskInfo)
  ))
_sym_db.RegisterMessage(TaskInfo)

TaskResult = _reflection.GeneratedProtocolMessageType('TaskResult', (_message.Message,), dict(
  DESCRIPTOR = _TASKRESULT,
  __module__ = 'proto.pbpipes_pb2'
  # @@protoc_insertion_point(class_scope:pbpipes.proto.TaskResult)
  ))
_sym_db.RegisterMessage(TaskResult)

ExecutorSpec = _reflection.GeneratedProtocolMessageType('ExecutorSpec', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTORSPEC,
  __module__ = 'proto.pbpipes_pb2'
  # @@protoc_insertion_point(class_scope:pbpipes.proto.ExecutorSpec)
  ))
_sym_db.RegisterMessage(ExecutorSpec)

DriverConfig = _reflection.GeneratedProtocolMessageType('DriverConfig', (_message.Message,), dict(
  DESCRIPTOR = _DRIVERCONFIG,
  __module__ = 'proto.pbpipes_pb2'
  # @@protoc_insertion_point(class_scope:pbpipes.proto.DriverConfig)
  ))
_sym_db.RegisterMessage(DriverConfig)


# @@protoc_insertion_point(module_scope)
